[server]
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#10B981"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#F1F5F9"
font = "sans serif"
